### ISSUE TITLE
Can't compile on c++ (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0

### ISSUE THREAD

**Issue by EyeOfPython** [LogosFoundation/lotusd#211]
Getting this error:

```
FAILED: src/CMakeFiles/common.dir/addresses/xaddress.cpp.o 
/usr/bin/c++ -DBOOST_AC_USE_STD_ATOMIC -DBOOST_SP_USE_STD_ATOMIC -DBUILD_BITCOIN_INTERNAL -DENABLE_AVX2 -DENABLE_SHANI -DENABLE_SSE41 -DHAVE_BUILD_INFO -DHAVE_CONFIG_H -DHAVE_CONSENSUS_LIB -I../src/. -Isrc -I../src/univalue/include -Isrc/crypto/.. -I../src/secp256k1/include -g -O2 -fPIC -fvisibility=hidden -fstack-reuse=none -fstack-protector-all -Wstack-protector -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -Wall -Wextra -Wformat -Wvla -Wcast-align -Wunused-parameter -Wmissing-braces -Wredundant-decls -Wsign-compare -Wformat-security -Wno-unused-parameter -Wno-implicit-fallthrough -pthread -std=gnu++1z -MD -MT src/CMakeFiles/common.dir/addresses/xaddress.cpp.o -MF src/CMakeFiles/common.dir/addresses/xaddress.cpp.o.d -o src/CMakeFiles/common.dir/addresses/xaddress.cpp.o -c ../src/addresses/xaddress.cpp
../src/addresses/xaddress.cpp: In function ‘XAddress::DecodeError XAddress::Decode(const string&, XAddress::Content&)’:
../src/addresses/xaddress.cpp:80:70: error: class template argument deduction failed:
                            std::vector(vch.begin() + 1, vch.end() - 4));
                                                                      ^
../src/addresses/xaddress.cpp:80:70: error: no matching function for call to ‘vector(__gnu_cxx::__normal_iterator<unsigned char*, std::vector<unsigned char> >, __gnu_cxx::__normal_iterator<unsigned char*, std::vector<unsigned char> >)’
In file included from /usr/include/c++/7/vector:64:0,
                 from ../src/./uint256.h:13,
                 from ../src/./primitives/blockhash.h:8,
                 from ../src/./consensus/params.h:9,
                 from ../src/./chainparams.h:10,
                 from ../src/./addresses/xaddress.h:8,
                 from ../src/addresses/xaddress.cpp:5:
/usr/include/c++/7/bits/stl_vector.h:411:2: note: candidate: template<class _Tp, class _Alloc, class _InputIterator, class> vector(_InputIterator, _InputIterator, const _Alloc&)-> std::vector<_Tp, _Alloc>
  vector(_InputIterator __first, _InputIterator __last,
  ^~~~~~
/usr/include/c++/7/bits/stl_vector.h:411:2: note:   template argument deduction/substitution failed:
../src/addresses/xaddress.cpp:80:70: note:   couldn't deduce template parameter ‘_Tp’
                            std::vector(vch.begin() + 1, vch.end() - 4));
                                                                      ^
In file included from /usr/include/c++/7/vector:64:0,
                 from ../src/./uint256.h:13,
                 from ../src/./primitives/blockhash.h:8,
                 from ../src/./consensus/params.h:9,
                 from ../src/./chainparams.h:10,
                 from ../src/./addresses/xaddress.h:8,
                 from ../src/addresses/xaddress.cpp:5:
/usr/include/c++/7/bits/stl_vector.h:383:7: note: candidate: template<class _Tp, class _Alloc> vector(std::initializer_list<_Tp>, const allocator_type&)-> std::vector<_Tp, _Alloc>
       vector(initializer_list<value_type> __l,
       ^~~~~~
/usr/include/c++/7/bits/stl_vector.h:383:7: note:   template argument deduction/substitution failed:
../src/addresses/xaddress.cpp:80:70: note:   ‘__gnu_cxx::__normal_iterator<unsigned char*, std::vector<unsigned char> >’ is not derived from ‘std::initializer_list<_Tp>’
                            std::vector(vch.begin() + 1, vch.end() - 4));
                                                                      ^
In file included from /usr/include/c++/7/vector:64:0,
                 from ../src/./uint256.h:13,
                 from ../src/./primitives/blockhash.h:8,
                 from ../src/./consensus/params.h:9,
                 from ../src/./chainparams.h:10,
                 from ../src/./addresses/xaddress.h:8,
                 from ../src/addresses/xaddress.cpp:5:
/usr/include/c++/7/bits/stl_vector.h:358:7: note: candidate: template<class _Tp, class _Alloc> vector(std::vector<_Tp, _Alloc>&&, const allocator_type&)-> std::vector<_Tp, _Alloc>
       vector(vector&& __rv, const allocator_type& __m)
       ^~~~~~
/usr/include/c++/7/bits/stl_vector.h:358:7: note:   template argument deduction/substitution failed:
../src/addresses/xaddress.cpp:80:70: note:   ‘__gnu_cxx::__normal_iterator<unsigned char*, std::vector<unsigned char> >’ is not derived from ‘std::vector<_Tp, _Alloc>’
                            std::vector(vch.begin() + 1, vch.end() - 4));
                                                                      ^
In file included from /usr/include/c++/7/vector:64:0,
                 from ../src/./uint256.h:13,
                 from ../src/./primitives/blockhash.h:8,
                 from ../src/./consensus/params.h:9,
                 from ../src/./chainparams.h:10,
                 from ../src/./addresses/xaddress.h:8,
                 from ../src/addresses/xaddress.cpp:5:
/usr/include/c++/7/bits/stl_vector.h:348:7: note: candidate: template<class _Tp, class _Alloc> vector(const std::vector<_Tp, _Alloc>&, const allocator_type&)-> std::vector<_Tp, _Alloc>
       vector(const vector& __x, const allocator_type& __a)
       ^~~~~~
/usr/include/c++/7/bits/stl_vector.h:348:7: note:   template argument deduction/substitution failed:
../src/addresses/xaddress.cpp:80:70: note:   ‘__gnu_cxx::__normal_iterator<unsigned char*, std::vector<unsigned char> >’ is not derived from ‘const std::vector<_Tp, _Alloc>’
                            std::vector(vch.begin() + 1, vch.end() - 4));
                                                                      ^
In file included from /usr/include/c++/7/vector:64:0,
                 from ../src/./uint256.h:13,
                 from ../src/./primitives/blockhash.h:8,
                 from ../src/./consensus/params.h:9,
                 from ../src/./chainparams.h:10,
                 from ../src/./addresses/xaddress.h:8,
                 from ../src/addresses/xaddress.cpp:5:
/usr/include/c++/7/bits/stl_vector.h:344:7: note: candidate: template<class _Tp, class _Alloc> vector(std::vector<_Tp, _Alloc>&&)-> std::vector<_Tp, _Alloc>
       vector(vector&& __x) noexcept
       ^~~~~~
/usr/include/c++/7/bits/stl_vector.h:344:7: note:   template argument deduction/substitution failed:
../src/addresses/xaddress.cpp:80:70: note:   ‘__gnu_cxx::__normal_iterator<unsigned char*, std::vector<unsigned char> >’ is not derived from ‘std::vector<_Tp, _Alloc>’
                            std::vector(vch.begin() + 1, vch.end() - 4));
                                                                      ^
In file included from /usr/include/c++/7/vector:64:0,
                 from ../src/./uint256.h:13,
                 from ../src/./primitives/blockhash.h:8,
                 from ../src/./consensus/params.h:9,
                 from ../src/./chainparams.h:10,
                 from ../src/./addresses/xaddress.h:8,
                 from ../src/addresses/xaddress.cpp:5:
/usr/include/c++/7/bits/stl_vector.h:326:7: note: candidate: template<class _Tp, class _Alloc> vector(const std::vector<_Tp, _Alloc>&)-> std::vector<_Tp, _Alloc>
       vector(const vector& __x)
       ^~~~~~
/usr/include/c++/7/bits/stl_vector.h:326:7: note:   template argument deduction/substitution failed:
../src/addresses/xaddress.cpp:80:70: note:   ‘__gnu_cxx::__normal_iterator<unsigned char*, std::vector<unsigned char> >’ is not derived from ‘const std::vector<_Tp, _Alloc>’
                            std::vector(vch.begin() + 1, vch.end() - 4));
                                                                      ^
In file included from /usr/include/c++/7/vector:64:0,
                 from ../src/./uint256.h:13,
                 from ../src/./primitives/blockhash.h:8,
                 from ../src/./consensus/params.h:9,
                 from ../src/./chainparams.h:10,
                 from ../src/./addresses/xaddress.h:8,
                 from ../src/addresses/xaddress.cpp:5:
/usr/include/c++/7/bits/stl_vector.h:295:7: note: candidate: template<class _Tp, class _Alloc> vector(std::vector<_Tp, _Alloc>::size_type, const value_type&, const allocator_type&)-> std::vector<_Tp, _Alloc>
       vector(size_type __n, const value_type& __value,
       ^~~~~~
/usr/include/c++/7/bits/stl_vector.h:295:7: note:   template argument deduction/substitution failed:
../src/addresses/xaddress.cpp:80:52: note:   cannot convert ‘vch.std::vector<unsigned char>::begin().__gnu_cxx::__normal_iterator<unsigned char*, std::vector<unsigned char> >::operator+(1)’ (type ‘__gnu_cxx::__normal_iterator<unsigned char*, std::vector<unsigned char> >’) to type ‘std::vector<_Tp, _Alloc>::size_type {aka long unsigned int}’
                            std::vector(vch.begin() + 1, vch.end() - 4));
                                        ~~~~~~~~~~~~^~~
In file included from /usr/include/c++/7/vector:64:0,
                 from ../src/./uint256.h:13,
                 from ../src/./primitives/blockhash.h:8,
                 from ../src/./consensus/params.h:9,
                 from ../src/./chainparams.h:10,
                 from ../src/./addresses/xaddress.h:8,
                 from ../src/addresses/xaddress.cpp:5:
/usr/include/c++/7/bits/stl_vector.h:283:7: note: candidate: template<class _Tp, class _Alloc> vector(std::vector<_Tp, _Alloc>::size_type, const allocator_type&)-> std::vector<_Tp, _Alloc>
       vector(size_type __n, const allocator_type& __a = allocator_type())
       ^~~~~~
/usr/include/c++/7/bits/stl_vector.h:283:7: note:   template argument deduction/substitution failed:
../src/addresses/xaddress.cpp:80:70: note:   couldn't deduce template parameter ‘_Tp’
                            std::vector(vch.begin() + 1, vch.end() - 4));
                                                                      ^
In file included from /usr/include/c++/7/vector:64:0,
                 from ../src/./uint256.h:13,
                 from ../src/./primitives/blockhash.h:8,
                 from ../src/./consensus/params.h:9,
                 from ../src/./chainparams.h:10,
                 from ../src/./addresses/xaddress.h:8,
                 from ../src/addresses/xaddress.cpp:5:
/usr/include/c++/7/bits/stl_vector.h:270:7: note: candidate: template<class _Tp, class _Alloc> vector(const allocator_type&)-> std::vector<_Tp, _Alloc>
       vector(const allocator_type& __a) _GLIBCXX_NOEXCEPT
       ^~~~~~
/usr/include/c++/7/bits/stl_vector.h:270:7: note:   template argument deduction/substitution failed:
../src/addresses/xaddress.cpp:80:70: note:   candidate expects 1 argument, 2 provided
                            std::vector(vch.begin() + 1, vch.end() - 4));
                                                                      ^
In file included from /usr/include/c++/7/vector:64:0,
                 from ../src/./uint256.h:13,
                 from ../src/./primitives/blockhash.h:8,
                 from ../src/./consensus/params.h:9,
                 from ../src/./chainparams.h:10,
                 from ../src/./addresses/xaddress.h:8,
                 from ../src/addresses/xaddress.cpp:5:
/usr/include/c++/7/bits/stl_vector.h:259:7: note: candidate: template<class _Tp, class _Alloc> vector()-> std::vector<_Tp, _Alloc>
       vector()
       ^~~~~~
/usr/include/c++/7/bits/stl_vector.h:259:7: note:   template argument deduction/substitution failed:
../src/addresses/xaddress.cpp:80:70: note:   candidate expects 0 arguments, 2 provided
                            std::vector(vch.begin() + 1, vch.end() - 4));
                                                                      ^
../src/addresses/xaddress.cpp:80:70: error: expression list treated as compound expression in functional cast [-fpermissive]
[207/303] Building CXX object src/CMakeFiles/server.dir/validation.cpp.o
ninja: build stopped: subcommand failed.
```
